version: '3.8'

services:
  wce-portail:
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wce-portail
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # command: npm run dev